// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJB5qQ5nfzDOmqNg8bqWMYT-JgEH042d0',
    appId: '1:492332713820:web:52df4a8b7bfc88860c2399',
    messagingSenderId: '492332713820',
    projectId: 'mediremind-6cce9',
    authDomain: 'mediremind-6cce9.firebaseapp.com',
    storageBucket: 'mediremind-6cce9.firebasestorage.app',
    measurementId: 'G-VHE99G3C4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7oMOZkzN2iPJSvgfvOTop_R8GKjHWKD4',
    appId: '1:492332713820:android:e814822c4e01020f0c2399',
    messagingSenderId: '492332713820',
    projectId: 'mediremind-6cce9',
    storageBucket: 'mediremind-6cce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlgls0qDvOwIv_VWC_6fI0q3KibHCQNY',
    appId: '1:492332713820:ios:9281dbdfd08c9ac70c2399',
    messagingSenderId: '492332713820',
    projectId: 'mediremind-6cce9',
    storageBucket: 'mediremind-6cce9.firebasestorage.app',
    iosBundleId: 'com.example.mediremind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlgls0qDvOwIv_VWC_6fI0q3KibHCQNY',
    appId: '1:492332713820:ios:9281dbdfd08c9ac70c2399',
    messagingSenderId: '492332713820',
    projectId: 'mediremind-6cce9',
    storageBucket: 'mediremind-6cce9.firebasestorage.app',
    iosBundleId: 'com.example.mediremind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJB5qQ5nfzDOmqNg8bqWMYT-JgEH042d0',
    appId: '1:492332713820:web:fd662f4a6c55c1670c2399',
    messagingSenderId: '492332713820',
    projectId: 'mediremind-6cce9',
    authDomain: 'mediremind-6cce9.firebaseapp.com',
    storageBucket: 'mediremind-6cce9.firebasestorage.app',
    measurementId: 'G-0S9HTQECK7',
  );
}
